### ISSUE TITLE
` --remote-rp` option fails with `ConnectionRefusedError`

### ISSUE THREAD

**Issue by bleykauf** [linien-org/linien#309]
Using the `--remote-rp` option does not work currently.

```
(linien) PS C:\Users\bastian\Documents\programming\linien> linien-server --remote-rp=root:***@rp-f07734.local
Start server on port 18862
Process Process-1:
Traceback (most recent call last):
  File "C:\Users\bastian\miniconda3\envs\linien\lib\multiprocessing\process.py", line 314, in _bootstrap
    self.run()
  File "C:\Users\bastian\miniconda3\envs\linien\lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "c:\users\bastian\documents\programming\linien\linien-server\linien_server\acquisition.py", line 81, in connect_acquisition_process
    acquisition_rpyc = rpyc.connect(host, ACQUISITION_PORT)
  File "C:\Users\bastian\miniconda3\envs\linien\lib\site-packages\rpyc\utils\factory.py", line 98, in connect
    s = SocketStream.connect(host, port, ipv6=ipv6, keepalive=keepalive)
  File "C:\Users\bastian\miniconda3\envs\linien\lib\site-packages\rpyc\core\stream.py", line 172, in connect
    return cls(cls._connect(host, port, **kwargs))
  File "C:\Users\bastian\miniconda3\envs\linien\lib\site-packages\rpyc\core\stream.py", line 124, in _connect
    s = socket_backoff_connect(family, socktype, proto, sockaddr, timeout, attempts)
  File "C:\Users\bastian\miniconda3\envs\linien\lib\site-packages\rpyc\lib\__init__.py", line 131, in socket_backoff_connect
    sock.connect(addr)
ConnectionRefusedError: [WinError 10061] No connection could be made because the target machine actively refused it
```

**Comment by bleykauf** [comment]
Actually seems to work fine, updating the wiki
