### ISSUE TITLE
Does not work on RedPitaya OS 2.0

### ISSUE THREAD

**Issue by bleykauf** [linien-org/linien#322]
Acquisition fails on RedPitaya OS 2.0 beta with v0.7.0:

```
root@rp-f09c32:~# linien-server
Start server on port 18862
restore parameters
ping 1
Exception in thread Thread-1 (receive_acquired_data):
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.10/dist-packages/linien_server/acquisition.py", line 53, in receive_acquired_data
    is_raw, received_data, data_uuid = conn.recv()
  File "/usr/lib/python3.10/multiprocessing/connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "/usr/lib/python3.10/multiprocessing/connection.py", line 414, in _recv_bytes
    buf = self._recv(4)
  File "/usr/lib/python3.10/multiprocessing/connection.py", line 379, in _recv
    chunk = read(handle, remaining)
ConnectionResetError: [Errno 104] Connection reset by peer
ping 2
^C
keyboard interrupt!
Exception ignored in atexit callback: <bound method AcquisitionMaster.shutdown of <linien_server.acquisition.AcquisitionMaster object at 0xaec98fe8>>
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/linien_server/acquisition.py", line 140, in shutdown
    self.parent_conn.send((AcquisitionProcessSignals.SHUTDOWN,))
  File "/usr/lib/python3.10/multiprocessing/connection.py", line 206, in send
    self._send_bytes(_ForkingPickler.dumps(obj))
  File "/usr/lib/python3.10/multiprocessing/connection.py", line 411, in _send_bytes
    self._send(header + buf)
  File "/usr/lib/python3.10/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
save parameters
root@rp-f09c32:~# linien-server --version
linien-server, version 0.7.0
```

on the command line. If this is successful, in order to to  check whether the
`linien-server` is running, first confirm that there is a running `screen` session with
the name `linien-server` by  executing `screen -ls`. If that is the case attach it by
running `screen -r linien-server`. If any errors occurred on the server side, they will
be displayed here. Please provide the output in your bug report.

**Comment by bleykauf** [comment]
Actually, the problem was somewhere else, see #342. Closed.
