### ISSUE TITLE
Installation of requests fails when using pip3 9.0.1

### ISSUE THREAD

**Issue by bleykauf** [linien-org/linien#339]
RedPitaya OS 1.04 ships with pip3 version 9.0.1. Attempting to install the `requests` package results in the following error when importing the package:

```
 root@rp-f09b78:~/linien/linien-server# linien-server
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/certifi/core.py", line 14, in <module>
    from importlib.resources import path as get_path, read_text
ImportError: No module named 'importlib.resources'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/linien-server", line 9, in <module>
    load_entry_point('linien-server', 'console_scripts', 'linien-server')()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 542, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2569, in load_entry_point
    return ep.load()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2229, in load
    return self.resolve()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2235, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/root/linien/linien-server/linien_server/server.py", line 36, in <module>
    from linien_server.influxdb import InfluxDBLogger
  File "/root/linien/linien-server/linien_server/influxdb.py", line 23, in <module>
    import requests
  File "/usr/local/lib/python3.5/dist-packages/requests/__init__.py", line 118, in <module>
    from . import utils
  File "/usr/local/lib/python3.5/dist-packages/requests/utils.py", line 25, in <module>
    from . import certs
  File "/usr/local/lib/python3.5/dist-packages/requests/certs.py", line 15, in <module>
    from certifi import where
  File "/usr/local/lib/python3.5/dist-packages/certifi/__init__.py", line 1, in <module>
    from .core import contents, where
  File "/usr/local/lib/python3.5/dist-packages/certifi/core.py", line 46, in <module>
    Resource = Union[str, "os.PathLike"]
  File "/usr/lib/python3.5/typing.py", line 552, in __getitem__
    dict(self.__dict__), parameters, _root=True)
  File "/usr/lib/python3.5/typing.py", line 512, in __new__
    for t2 in all_params - {t1} if not isinstance(t2, TypeVar)):
  File "/usr/lib/python3.5/typing.py", line 512, in <genexpr>
    for t2 in all_params - {t1} if not isinstance(t2, TypeVar)):
  File "/usr/lib/python3.5/typing.py", line 190, in __subclasscheck__
    self._eval_type(globalns, localns)
  File "/usr/lib/python3.5/typing.py", line 177, in _eval_type
    eval(self.__forward_code__, globalns, localns),
  File "<string>", line 1, in <module>
AttributeError: module 'os' has no attribute 'PathLike'
```

Adding a higher pip version as a requirement to the `setup.py` does not work, presumably because pip 9.0.1 is still used to install requests. Updating pip3 prior to installing `linien-server` works, however.

**Comment by bleykauf** [comment]
Resolved by pinning version of certifi in https://github.com/linien-org/linien/commit/c4586db4362818043f4420842b14b478dfc4782f.
