### ISSUE TITLE
TypeError: can't pickle _thread.lock objects in v0.8.0rc2

### ISSUE THREAD

**Issue by bleykauf** [linien-org/linien#341]
When attempting to lock:

```
Traceback (most recent call last):
  File "c:\users\bastianleykauf\documents\programming\linien\linien-gui\linien_gui\app.py", line 70, in periodically_check_for_changed_parameters
    self.parameters.check_for_changed_parameters()
  File "c:\users\bastianleykauf\documents\programming\linien\linien-client\linien_client\connection.py", line 165, in wrapped
    return method(*args, **kwargs)
  File "c:\users\bastianleykauf\documents\programming\linien\linien-client\linien_client\remote_parameters.py", line 194, in check_for_changed_parameters        
    self._async_changed_parameters_queue.value
  File "C:\Users\BastianLeykauf\miniconda3\envs\linien\lib\site-packages\rpyc\core\async_.py", line 102, in value
    raise self._obj
_get_exception_class.<locals>.Derived: can't pickle _thread.lock objects

========= Remote Traceback (1) =========
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/rpyc/core/protocol.py", line 320, in _dispatch_request
    res = self._HANDLERS[handler](self, *args)
  File "/usr/local/lib/python3.5/dist-packages/rpyc/core/protocol.py", line 593, in _handle_call
    return obj(*args, **dict(kwargs))
  File "/usr/local/lib/python3.5/dist-packages/linien_server/server.py", line 97, in exposed_get_changed_parameters_queue
    return pickle.dumps(self.parameters.get_changed_parameters_queue(uuid))
TypeError: can't pickle _thread.lock objects


```

**Comment by bleykauf** [comment]
After closing and reconnection attempt:

```
Traceback (most recent call last):
  File "c:\users\bastianleykauf\documents\programming\linien\linien-gui\linien_gui\threads.py", line 88, in run
    self.client.connect(
  File "c:\users\bastianleykauf\documents\programming\linien\linien-client\linien_client\connection.py", line 98, in connect
    self.parameters = cls(
  File "c:\users\bastianleykauf\documents\programming\linien\linien-client\linien_client\remote_parameters.py", line 116, in __init__
    self.remote.exposed_init_parameter_sync(self.uuid)
  File "C:\Users\BastianLeykauf\miniconda3\envs\linien\lib\site-packages\rpyc\core\netref.py", line 253, in __call__
    return syncreq(_self, consts.HANDLE_CALL, args, kwargs)
  File "C:\Users\BastianLeykauf\miniconda3\envs\linien\lib\site-packages\rpyc\core\netref.py", line 76, in syncreq
    return conn.sync_request(handler, proxy, *args)
  File "C:\Users\BastianLeykauf\miniconda3\envs\linien\lib\site-packages\rpyc\core\protocol.py", line 469, in sync_request
    return self.async_request(handler, *args, timeout=timeout).value
  File "C:\Users\BastianLeykauf\miniconda3\envs\linien\lib\site-packages\rpyc\core\async_.py", line 102, in value
    raise self._obj
_get_exception_class.<locals>.Derived: can't pickle _thread.lock objects

========= Remote Traceback (1) =========
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/rpyc/core/protocol.py", line 320, in _dispatch_request
    res = self._HANDLERS[handler](self, *args)
  File "/usr/local/lib/python3.5/dist-packages/rpyc/core/protocol.py", line 593, in _handle_call
    return obj(*args, **dict(kwargs))
  File "/usr/local/lib/python3.5/dist-packages/linien_server/server.py", line 85, in exposed_init_parameter_sync
    return pickle.dumps(list(self.parameters.init_parameter_sync(uuid)))
TypeError: can't pickle _thread.lock objects
```

**Comment by bleykauf** [comment]
When attempting to optimize:

```
Traceback (most recent call last):
  File "c:\users\bastianleykauf\documents\programming\linien\linien-gui\linien_gui\app.py", line 70, in periodically_check_for_changed_parameters
    self.parameters.check_for_changed_parameters()
  File "c:\users\bastianleykauf\documents\programming\linien\linien-client\linien_client\connection.py", line 165, in wrapped
    return method(*args, **kwargs)
  File "c:\users\bastianleykauf\documents\programming\linien\linien-client\linien_client\remote_parameters.py", line 194, in check_for_changed_parameters        
    self._async_changed_parameters_queue.value
  File "C:\Users\BastianLeykauf\miniconda3\envs\linien\lib\site-packages\rpyc\core\async_.py", line 102, in value
    raise self._obj
_get_exception_class.<locals>.Derived: can't pickle _thread.lock objects

========= Remote Traceback (1) =========
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/rpyc/core/protocol.py", line 320, in _dispatch_request
    res = self._HANDLERS[handler](self, *args)
  File "/usr/local/lib/python3.5/dist-packages/rpyc/core/protocol.py", line 593, in _handle_call
    return obj(*args, **dict(kwargs))
  File "/usr/local/lib/python3.5/dist-packages/linien_server/server.py", line 97, in exposed_get_changed_parameters_queue
    return pickle.dumps(self.parameters.get_changed_parameters_queue(uuid))
TypeError: can't pickle _thread.lock objects
```

**Comment by bleykauf** [comment]
Closed for now, but wer are using bare excepts again
