### ISSUE TITLE
Status of the feature/add-relock branch

### ISSUE THREAD

**Issue by ograsdijk** [linien-org/linien#430]
What's the current status of the [feature/add-relock](https://github.com/linien-org/linien/tree/feature/add-relock) branch?

We tried to run it in our lab; but had the following error when starting linien-server on the red pitaya manually, with `linien-server run`.
`mdio-tools` is installed and accessible from the command line.
```
Traceback (most recent call last):
  File "/usr/local/bin/linien-server", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/dist-packages/linien_server/cli.py", line 113, in main
    fire.Fire(LinienServerCLI)
  File "/usr/local/lib/python3.10/dist-packages/fire/core.py", line 143, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/usr/local/lib/python3.10/dist-packages/fire/core.py", line 477, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/usr/local/lib/python3.10/dist-packages/fire/core.py", line 693, in CallAndUpdateTrace
    component = fn(varargs, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/linien_server/cli.py", line 96, in run
    mdio_tool.enable_ethernet_blinking()
  File "/usr/local/lib/python3.10/dist-packages/linien_server/mdio_tool.py", line 33, in enable_ethernet_blinking
    subprocess.run([f"{binary_path}", "w", "eth0", "0x1b", "0x0f00"])
  File "/usr/lib/python3.10/subprocess.py", line 501, in run
    with Popen(popenargs, **kwargs) as process:
  File "/usr/lib/python3.10/subprocess.py", line 969, in _init
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.10/subprocess.py", line 1845, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
OSError: [Errno 8] Exec format error: '/usr/local/lib/python3.10/dist-packages/linien_server/mdio-tool'
```

**Comment by alekkemeny** [comment]
@bleykauf bumping this. We are also interested in the status of the autolocking feature for use in our lab.
